config/routes.rb
Rails.application.routes.draw do
	devise_for :admin_users, ActiveAdmin::Devise.config
	match 'admin/results/update_subjects' => 'admin/results#update_subjects', via: [:get,:post], :as => :admin_update_subjects
	ActiveAdmin.routes(self)

	root 'ideal_institute#index'

		get 'ideal_institute/index' => 'ideal_institute#index'
		get 'ideal_institute/about-us' => 'ideal_institute#about-us'
		get 'ideal_institute/accreditations' => 'ideal_institute#accreditations'
		get 'ideal_institute/contact_us' => 'ideal_institute#contact_us'
		get 'ideal_institute/courses' => 'ideal_institute#courses'
		get 'ideal_institute/policy' => 'ideal_institute#policy'
		get 'ideal_institute/procedure' => 'ideal_institute#procedure'
		get 'ideal_institute/refund' => 'ideal_institute#refund'
		get 'ideal_institute/terms' => 'ideal_institute#terms'
		get 'ideal_institute/training-placement' => 'ideal_institute#training-placement'
		get 'ideal_institute/universities' => 'ideal_institute#universities'
		get 'ideal_institute/verification' => 'ideal_institute#verification'
		post 'ideal_institute/marks_detail' => 'ideal_institute#marks_detail'
		get 'ideal_institute/show_pdf' => 'ideal_institute#show_pdf'
		match 'ideal_institute/contact_u' => 'ideal_institute#contact_u', via: [:get, :post]

end

app/models/account_detail.rb
class AccountDetail < ActiveRecord::Base
	mount_uploader :payment_copy, ImageUploader
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
	validates :name,:email,:message,:phone_no, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/courier_detail.rb
class CourierDetail < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
	validates :name,:duration,:fee, presence: true
	has_many :subjects, :dependent => :destroy
	has_many :students, :dependent => :destroy
end

app/models/mark.rb
class Mark < ActiveRecord::Base
	belongs_to :subject
	belongs_to :result
end

app/models/result.rb
class Result < ActiveRecord::Base
	validates :certificate_no, presence: true
	belongs_to :student
	has_many :marks, :dependent => :destroy
	has_many :subjects, through: :marks
	accepts_nested_attributes_for :marks
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :course_id,:university_id,:name,:dob,:gender,:session, presence: true
	belongs_to :university	
	belongs_to :course
	has_one :result, :dependent => :destroy
	before_create :generate_enrolment_no
	mount_uploader :image, ImageUploader

	protected
		def generate_enrolment_no
			begin
				base_code = SecureRandom.random_number
				# base_code.gsub!(/[^\w]|[iILloO01]/,'')
				code = base_code.to_s[2..5]
				code= "IEIMT-DEL"+code
				# binding.pry
			end while Student.where(enrolment_no: code).exists?
			self.enrolment_no = code
		end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	validates :name,:code, presence: true
	validates :code, uniqueness: true
	belongs_to :course
	has_many :marks, :dependent => :destroy
	has_many :results, through: :marks
	
end

app/models/university.rb
class University < ActiveRecord::Base
	validates :name,:university_type, presence: true
	has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	# def remote_ip
 #    if request.remote_ip == '127.0.0.1'
 #      '123.45.67.89'
 #    else
 #      request.remote_ip
 #    end
 #  end

end

app/controllers/ideal_institute_controller.rb
class IdealInstituteController < ApplicationController

	# def download
	# 	@client_ip = remote_ip()
 #  	send_file(
 #    	"#{Rails.root}/public/management.pdf",
 #    	filename: "management.pdf",
 #    	type: "application/pdf"
 # 	 	)
	# end

	def show_pdf
		if params[:course_type] == "management"
		  pdf_filename = File.join(Rails.root, "public/ieimt_management_details.pdf")
		  send_file(pdf_filename, :filename => "ieimt_management_details.pdf", :disposition => 'inline', :type => "application/pdf")
		end
		if params[:course_type] == "engineering"
		  pdf_filename = File.join(Rails.root, "public/ieimt_engineering_details.pdf")
		  send_file(pdf_filename, :filename => "ieimt_engineering_details.pdf", :disposition => 'inline', :type => "application/pdf")
		end
		if params[:admission_form] == "gcl_form"
		  pdf_filename = File.join(Rails.root, "public/form.pdf")
		  send_file(pdf_filename, :filename => "form.pdf", :disposition => 'inline', :type => "application/pdf")
		end
	end

	def universities
		# if params[:university_type] == "Regular University"
		# 	@universities = University.where university_type: "Regular University"
		# end
		# if params[:university_type] == "Distance University"
		# 	@universities = University.where university_type: "Distance University"
		# end
	end

	def contact_us
		@contact_us = ContactU.new
	end

	def contact_u
	 	@contact_us = ContactU.new(contact_params)
	 	if @contact_us.valid?
	 		@contact_us.save
	 		# ContactusMailer.contact_email(@contact_us).deliver_now
	 	end 
		redirect_to ideal_institute_contact_us_path
	end

	def marks_detail
		if !(params[:enrolment_no] && params[:dob]).blank?
			@student = Student.find_by enrolment_no: params[:enrolment_no]
			if @student.present? && @student.dob.to_time.strftime("%d/%m/%Y") == params[:dob].to_time.strftime("%d/%m/%Y")				
				@result = @student.result
				# if !@result.present?
				# 	return :back
				# end
			else
				redirect_to ideal_institute_verification_path
			end
		else
			redirect_to ideal_institute_verification_path
		end
	end

	private
  def contact_params
    params.require(:contact_u).permit(:name, :email, :phone_no, :city, :country, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def remote_request(type, path, params={}, target_tag_id)
  "$.#{type}('#{path}',
	   {#{params.collect { |p| "#{p[0]}: #{p[1]}" }.join(", ")}},
	   function(data) {$('##{target_tag_id}').html(data);}
   );"
	end
end

app/helpers/ideal_institute_helper.rb
module IdealInstituteHelper
end

app/views/admin/results/update_subjects.js.erb
$("#mm").html("<%= escape_javascript(render(:partial => 'subjects')) %>");

app/views/ideal_institute/about-us.html.erb
<div class="col-md-8">
	<div class="row top-header">
		<div class="col-md-4"></div>
		<div class="col-md-8">
			<ul class="inline-list">
				<li><%= link_to "Admin Login |", new_admin_user_session_path %></li>
				<li><%= link_to "Student Login |", new_admin_user_session_path %></li>
				<li><%= link_to "Enroll Now |", root_path %></li>
				<li><%= link_to "Home |",  ideal_institute_index_path %></li>
				<li class="active"><%= link_to "About Us |", ideal_institute_about_us_path %></li>
				<li><%= link_to "Contact Us", ideal_institute_contact_us_path %></li>
			</ul>
		</div>
	</div>
	<div class="row top-header main">
		<div class="col-md-8" style="padding-top: 1%;padding-bottom: 1%;">
			<div class="col-md-4">
				<style>.logo {width:%;}</style>
				<%= image_tag(('logo.png'), :class => "logo img-responsive") %>
			</div>
			<div class="col-md-8" style="padding-top: 4%;">	
				<h4 style="font-size: 24px;"><%= link_to "IDEAL EDUCATION INSTITUTE MANAGEMENT & TECHNOLOGY", ideal_institute_index_path %></h4>
			</div>
		</div>
		<div class="col-md-4" style="padding-top:3%;">
      <ul class="inline-list">
        <li><span style="font-size:12px;">Follow Us : </span></li>
        <li><a href="#" class="fa fa-facebook-square" style="font-size:24px;"></a></li>
        <li><a href="#" class="fa fa-twitter-square" style="font-size:24px;"></a></li>
        <li><a href="#" class="fa fa-google-plus-square" style="font-size:24px;"></a></li>
      </ul>
			<h5>Email Id : info@ieimt.org</h5>
    	<h5>Contact No.: 011-40554732, 9212900683</h5>
    </div>
		<div class="col-md-12">
			<nav class="navbar navbar-default">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="padding:0px;">
					<ul class="nav navbar-nav">
						<li>
							<a href="" class="dropdown-toggle" data-toggle="dropdown" >Courses & Fees <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Engineering Courses", ideal_institute_show_pdf_path(course_type: "engineering"), target: '_blank' %></li>
								<li><%= link_to "Management Courses", ideal_institute_show_pdf_path(course_type: "management"), target: '_blank' %></li>
							</ul>
						</li>
						<li><%= link_to "Procedure", ideal_institute_procedure_path %></li>
						<li><%= link_to "Accreditations", ideal_institute_accreditations_path %></li>
						<li><%= link_to "Training & Placement", ideal_institute_training_placement_path %></li>
						<li><%= link_to "Verification", ideal_institute_verification_path %></li>
						<li>
							<a href="" class="dropdown-toggle" data-toggle="dropdown">Universities <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%#= link_to "Regular Universities", ideal_institute_universities_path(university_type: "Regular University") %>
								<%= link_to "Regular Universities" %></li>
								<li><%#= link_to "Distance Universities", ideal_institute_universities_path(university_type: "Distance University") %>
								<%= link_to "Distance Universities", ideal_institute_universities_path %></li>
							</ul>
						</li>
						<li style="border-right: none;">
							<a href="" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "About us", ideal_institute_about_us_path %></li>
								<li><%= link_to "Contact us", ideal_institute_contact_us_path %></li>
								<li><%= link_to "Extras" %></li>
							</ul>
						</li>
					</ul>
				</div>
			</nav>
		</div>
		<div class="col-md-12" style="margin-top:20px;"></div>
		<div class="col-md-12 rt-content">
			<div class="box">
				<h4>About us</h4>
				<p>Ideal Education Management & Technology as distance education centers in Delhi was established by the Ideal Education Group , duly registered by the govt. of NCT of Delhi under Societies Registration act XXI of 1860.</p>
				<p>IEMT has been appointed as a UGC/AICTE and DEC approved Universities admission center to Facilitate Admissions in certificate, diploma, graduate and post – graduate courses like BSC, BBA, MBA, B.Tech, M.Tech, MCA, MCom, PHD, LLB, ITI and Polytechnic Diploma.</p>
				<p>IEMT offers you quality Distance Education Courses in Delhi to enhance your career, designed to provide you with specialist knowledge of international business, so that you get a truly international perspective, rather than one, that is solely relevant for one country. The wide range of electives allows you to build a program to meet your career objectives. The flexibility of these distance learning courses allows you to fit your studies around your personal and professional commitments.</p>
				<h4>Our Vision</h4>
				<p> we have pioneered the concepts of Distance Learning MBA .In future IEMT will be a world leader in preparing professionals who provide leadership and exemplary educational and related services to improve the lives of individuals in a changing and complex global society.</p>
				<h4>Our Mission</h4>
				<p>"To be the premier source for quality education, training, and professional certification, serving the needs and advancing the excellence of hospitality schools and industries worldwide."</p>
			</div>
		</div>
		<div class="col-md-12" style="margin-top:20px;"></div>
	</div>
	<div class="row top-header bottom ">
		<div class="col-md-12">
			<ul>
				<li><%= link_to "Privacy Policy |", ideal_institute_policy_path %></li>
				<li><%= link_to "Refund & Cancellation Policy |", ideal_institute_refund_path %></li>
				<li><%= link_to "Terms & Conditions |", ideal_institute_terms_path %></li>
				<li><%= link_to "Contact us", ideal_institute_contact_us_path %></li>
			</ul>
		</div>
		<div class="col-md-12">
			<ul>
				<li>Copyright &copy 2015. All rights reserved. |</li>
				<li>Ideal Education Institute Management & Technology.</li>
			</ul>
		</div>
	</div>
</div>

app/views/ideal_institute/contact_us.html.erb
<div class="col-md-8">
	<div class="row top-header">
		<div class="col-md-4"></div>
		<div class="col-md-8">
			<ul class="inline-list">
				<li><%= link_to "Admin Login |", new_admin_user_session_path %></li>
				<li><%= link_to "Student Login |", new_admin_user_session_path %></li>
        <li><%= link_to "Enroll Now |", root_path %></li>
        <li><%= link_to "Home |",  ideal_institute_index_path %></li>
        <li><%= link_to "About Us |", ideal_institute_about_us_path %></li>
        <li class="active"><%= link_to "Contact Us", ideal_institute_contact_us_path %></li>
			</ul>
		</div>
	</div>

	<div class="row top-header main">
		<div class="col-md-8" style="padding-top: 1%;padding-bottom: 1%;">
			<div class="col-md-4">
				<style>.logo {width:%;}</style>
				<%= image_tag(('logo.png'), :class => "logo img-responsive") %>
			</div>
			<div class="col-md-8" style="padding-top: 4%;">	
				<h4 style="font-size: 24px;"><%= link_to "IDEAL EDUCATION INSTITUTE MANAGEMENT & TECHNOLOGY", ideal_institute_index_path %></h4>
			</div>
		</div>
		<div class="col-md-4" style="padding-top:3%;">
      <ul class="inline-list">
        <li><span style="font-size:12px;">Follow Us : </span></li>
        <li><a href="#" class="fa fa-facebook-square" style="font-size:24px;"></a></li>
        <li><a href="#" class="fa fa-twitter-square" style="font-size:24px;"></a></li>
        <li><a href="#" class="fa fa-google-plus-square" style="font-size:24px;"></a></li>
      </ul>
			<h5>Email Id : info@ieimt.org</h5>
    	<h5>Contact No.: 011-40554732, 9212900683</h5>
    </div>

		<div class="col-md-12">
			<nav class="navbar navbar-default">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    </div>
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="padding:0px;">
		      <ul class="nav navbar-nav">

		        <li>
							<a href="" class="dropdown-toggle" data-toggle="dropdown">Courses & Fees <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Engineering Courses", ideal_institute_show_pdf_path(course_type: "engineering"), target: '_blank' %></li>
								<li><%= link_to "Management Courses", ideal_institute_show_pdf_path(course_type: "management"), target: '_blank' %></li>
							</ul>
						</li>
            <li><%= link_to "Procedure", ideal_institute_procedure_path %></li>
            <li><%= link_to "Accreditations", ideal_institute_accreditations_path %></li>
            <li><%= link_to "Training & Placement", ideal_institute_training_placement_path %></li>
            <li><%= link_to "Verification", ideal_institute_verification_path %></li>
		        <li>
							<a href="" class="dropdown-toggle" data-toggle="dropdown">Universities <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%#= link_to "Regular Universities", ideal_institute_universities_path(university_type: "Regular University") %>
								<%= link_to "Regular Universities" %></li>
								<li><%#= link_to "Distance Universities", ideal_institute_universities_path(university_type: "Distance University") %>
								<%= link_to "Distance Universities", ideal_institute_universities_path %></li>
							</ul>
						</li>
            <li style="border-right: none;">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "About us", ideal_institute_about_us_path %></li>
                <li><%= link_to "Contact us", ideal_institute_contact_us_path %></li>
                <li><%= link_to "Extras" %></li>
              </ul>
            </li>
		      </ul>
		    </div>
			</nav>
		</div>

		<div class="col-md-12" style="margin-top:20px;"></div>

		<div class="col-md-12 rt-content">
			<div class="box">
				<h4>Contact Us</h4>
				<%= form_for @contact_us, url: ideal_institute_contact_u_path, class: "form-horizontal" do |f| %>
					<div class="form-group">
					  <%= f.label :name, class: "col-sm-2 control-label" %>
					  <div class="col-sm-10">
					  	<%= f.text_field :name, placeholder: "Name", class: "form-control" %><br />
					  </div>
				  </div>
				  <div class="form-group">
					  <%= f.label :email, class: "col-sm-2 control-label" %>
					  <div class="col-sm-10">
					  	<%= f.email_field :email, placeholder: "Email", class: "form-control" %><br />
					  </div>
				  </div>
				  <div class="form-group">
					  <%= f.label :city, class: "col-sm-2 control-label" %>
					  <div class="col-sm-10">
					  	<%= f.text_field :city, placeholder: "City", class: "form-control" %><br />
					  </div>
				  </div>
				  <div class="form-group">
					  <%= f.label :country, class: "col-sm-2 control-label" %>
					  <div class="col-sm-10">
					  	<%= f.text_field :country, placeholder: "Country", class: "form-control" %><br />
					  </div>
				  </div>
				  <div class="form-group">
					  <%= f.label :phone_no, class: "col-sm-2 control-label" %>
					  <div class="col-sm-10">
					  	<%= f.telephone_field :phone_no, placeholder: "Phone Number", class: "form-control" %><br />
					  </div>
				  </div>
				  <div class="form-group">
					  <%= f.label :message, class: "col-sm-2 control-label" %>
					  <div class="col-sm-10">
					  	<%= f.text_area :message, placeholder: "Message", class: "form-control" %><br />
					  </div>
				  </div>
				  
				  <%= f.submit "Submit", class: "btn btn-default" %>
				<% end %>

				<!-- <form class="form-horizontal">
					<div class="form-group">
				    <label class="col-sm-2 control-label">Name :</label>
				    <div class="col-sm-10">
				      <input type="text" class="form-control" placeholder="Name">
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-2 control-label">Email :</label>
				    <div class="col-sm-10">
				      <input type="email" class="form-control" placeholder="Email">
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-2 control-label">City :</label>
				    <div class="col-sm-10">
				      <input type="text" class="form-control" placeholder="City">
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-2 control-label">Country :</label>
				    <div class="col-sm-10">
				      <input type="text" class="form-control" placeholder="Country">
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-2 control-label">Phone Number :</label>
				    <div class="col-sm-10">
				      <input type="number" class="form-control" placeholder="Phone Number">
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-2 control-label">Message :</label>
				    <div class="col-sm-10">
				  		<textarea class="form-control" rows="3" placeholder="Message"></textarea>
				  	</div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-2 col-sm-10">
				      <button type="submit" class="btn btn-default">Submit</button>
				    </div>
				  </div>
				</form> -->
				<h4>Contact Info</h4>
				<div class="row">
					<div class="col-md-5">
						<p><b><i>Address :</i></b></p>
						<p>Ideal Education Management & Technology</p>
						<p>92-H, 2nd Floor Pratap Market Munirka, New Delhi-110067</p>
					</div>
					<div class="col-md-2"></div>
					<div class="col-md-5">
						<p><b><i>Phone & Email :</i></b></p>
						<p> <i class="fa fa-phone"></i> 011-40554732, +91-9212900683</p>
						<p> <i class="fa fa-envelope"></i> info@ieimt.org </p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12" style="margin-top:20px;"></div>
	</div>
	<div class="row top-header bottom">
		<div class="col-md-12">
			<ul>
				<li><%= link_to "Privacy Policy |", ideal_institute_policy_path %></li>
        <li><%= link_to "Refund & Cancellation Policy |", ideal_institute_refund_path %></li>
        <li><%= link_to "Terms & Conditions |", ideal_institute_terms_path %></li>
        <li class="active"><%= link_to "Contact us", ideal_institute_contact_us_path %></li>
			</ul>
		</div>
		<div class="col-md-12">
			<ul>
				<li>Copyright &copy 2015. All rights reserved. |</li>
				<li>Ideal Education Institute Management & Technology.</li>
			</ul>
		</div>
	</div>
</div>

app/views/ideal_institute/verification.html.erb
<div class="col-md-8">
	<div class="row top-header">
		<div class="col-md-4"></div>
		<div class="col-md-8">
			<ul class="inline-list">
				<li><%= link_to "Admin Login |", new_admin_user_session_path %></li>
				<li><%= link_to "Student Login |", new_admin_user_session_path %></li>
				<li><%= link_to "Enroll Now |", root_path %></li>
				<li><%= link_to "Home |",  ideal_institute_index_path %></li>
				<li><%= link_to "About Us |", ideal_institute_about_us_path %></li>
				<li><%= link_to "Contact Us", ideal_institute_contact_us_path %></li>
			</ul>
		</div>
	</div>
	<div class="row top-header main">
		<div class="col-md-8" style="padding-top: 1%;padding-bottom: 1%;">
			<div class="col-md-4">
				<style>.logo {width:%;}</style>
				<%= image_tag(('logo.png'), :class => "logo img-responsive") %>
			</div>
			<div class="col-md-8" style="padding-top: 4%;">	
				<h4 style="font-size: 24px;"><%= link_to "IDEAL EDUCATION INSTITUTE MANAGEMENT & TECHNOLOGY", ideal_institute_index_path %></h4>
			</div>
		</div>
		<div class="col-md-4" style="padding-top:3%;">
      <ul class="inline-list">
        <li><span style="font-size:12px;">Follow Us : </span></li>
        <li><a href="#" class="fa fa-facebook-square" style="font-size:24px;"></a></li>
        <li><a href="#" class="fa fa-twitter-square" style="font-size:24px;"></a></li>
        <li><a href="#" class="fa fa-google-plus-square" style="font-size:24px;"></a></li>
      </ul>
			<h5>Email Id : info@ieimt.org</h5>
    	<h5>Contact No.: 011-40554732, 9212900683</h5>
    </div>
		<div class="col-md-12">
			<nav class="navbar navbar-default">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="padding:0px;">
					<ul class="nav navbar-nav">
						<li>
							<a href="" class="dropdown-toggle" data-toggle="dropdown">Courses & Fees <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Engineering Courses", ideal_institute_show_pdf_path(course_type: "engineering"), target: '_blank' %></li>
								<li><%= link_to "Management Courses", ideal_institute_show_pdf_path(course_type: "management"), target: '_blank' %></li>
							</ul>
						</li>
						<li><%= link_to "Procedure", ideal_institute_procedure_path %></li>
						<li><%= link_to "Accreditations", ideal_institute_accreditations_path %></li>
						<li><%= link_to "Training & Placement", ideal_institute_training_placement_path %></li>
						<li class="active"><%= link_to "Verification", ideal_institute_verification_path %></li>
						<li>
							<a href="" class="dropdown-toggle" data-toggle="dropdown">Universities <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%#= link_to "Regular Universities", ideal_institute_universities_path(university_type: "Regular University") %>
								<%= link_to "Regular Universities" %></li>
								<li><%#= link_to "Distance Universities", ideal_institute_universities_path(university_type: "Distance University") %>
								<%= link_to "Distance Universities", ideal_institute_universities_path %></li>
							</ul>
						</li>
						<li style="border-right: none;">
							<a href="" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "About us", ideal_institute_about_us_path %></li>
								<li><%= link_to "Contact us", ideal_institute_contact_us_path %></li>
								<li><%= link_to "Extras" %></li>
							</ul>
						</li>
					</ul>
				</div>
			</nav>
		</div>
		<div class="col-md-12" style="margin-top:20px;"></div>
		<div class="col-md-12 rt-content">
			<div class="box">
				<h4>Verification</h4>
				<%= form_tag(ideal_institute_marks_detail_path, method: "post") do %>
					<div class="form-group">
						<%= label_tag :enrolment_no, "Enrolment No. :" %>
						<%= text_field_tag :enrolment_no %>
					</div>
					<div class="form-group">
						<%= label_tag :dob, "Date of Birth :" %>
						<%= text_field_tag :dob, nil, class: "datepicker" %>
					</div>
					<%= submit_tag "Submit", class: "btn btn-default" %>
				<% end %>
				<p><b><i>For verification of your certificate please send mail <a href="#">verification@iemt.in</a></i></b></p>
			</div>
		</div>
		<div class="col-md-12" style="margin-top:20px;"></div>
	</div>
	<div class="row top-header bottom">
		<div class="col-md-12">
			<ul>
				<li><%= link_to "Privacy Policy |", ideal_institute_policy_path %></li>
				<li><%= link_to "Refund & Cancellation Policy |", ideal_institute_refund_path %></li>
				<li><%= link_to "Terms & Conditions |", ideal_institute_terms_path %></li>
				<li><%= link_to "Contact us", ideal_institute_contact_us_path %></li>
			</ul>
		</div>
		<div class="col-md-12">
			<ul>
				<li>Copyright &copy 2015. All rights reserved. |</li>
				<li>Ideal Education Institute Management & Technology.</li>
			</ul>
		</div>
	</div>
</div>